In [84]:
import tensorflow as tf

### Fase de construção

In [11]:
a = tf.constant(10, name = 'a')
b = tf.constant(20, name = 'b')

c = tf.add(a, b, name = 'soma')

### Fase de execução

In [12]:
s = tf.Session()
cval = s.run(c)
print cval
s.close()

30


In [13]:
with tf.Session() as s:
    print s.run(c)

30


In [14]:
with tf.Session() as s:
    print c.eval()

30


### Tensores

In [23]:
m1 = tf.constant([[1,2,3,4],[5,6,7,8]], name = 'm1')
m2 = tf.constant([[9,10,11,12],[13,14,15,16]], name = 'm2')

m3 = tf.add(m1, m2, name = 'soma')
m4 = tf.matmul(m1, tf.transpose(m2))

In [25]:
with tf.Session() as s:
    print s.run(m3)
    print s.run(m4)

[[10 12 14 16]
 [18 20 22 24]]
[[110 150]
 [278 382]]


In [85]:
m1 = tf.constant([[1,2,3,4],[5,6,7,8]], name = 'm1')
m2 = tf.constant([[9,10,11,12],[13,14,15,16]], name = 'm2')

m3 = tf.add(m1, m2, name = 'soma')
m4 = tf.matmul(m3, tf.transpose(m2))

In [88]:
with tf.Session() as s:
    vm3 = s.run(m3)
    vm4 = s.run(m4)
    print vm3
    print vm4

[[10 12 14 16]
 [18 20 22 24]]
[[ 556  764]
 [ 892 1228]]


In [90]:
with tf.Session() as s:
    vm3, vm4 = s.run([m3, m4])
    print vm3
    print vm4

[[10 12 14 16]
 [18 20 22 24]]
[[ 556  764]
 [ 892 1228]]


### Variáveis

In [27]:
contador = tf.Variable(0, dtype = tf.int32, name = 'contador')

In [35]:
with tf.Session() as s:
    s.run(contador.initializer)
    print s.run(contador)

0


In [36]:
contador = tf.Variable(0, dtype = tf.int32, name = 'contador')

init = tf.global_variables_initializer()

In [37]:
with tf.Session() as s:
    s.run(init)
    print s.run(contador)

0


In [39]:
def meurange(ini, fim):
    i = 0
    while i < fim:
        print i
        i += 1

In [40]:
meurange(0,4)

0
1
2
3


In [42]:
def tf_meurange(ini, fim):
    # construcao
    i = tf.Variable(ini, dtype = tf.int32, name = 'i')
    inc_i = tf.assign(i, tf.add(i, 1))
    init = tf.global_variables_initializer()
    
    # execucao
    with tf.Session() as s:
        s.run(init)
        vi = i.eval()
        while vi < fim:
            print vi
            s.run(inc_i)
            vi = i.eval()

In [43]:
tf_meurange(0,4)

0
1
2
3


### Placeholders

In [44]:
import pandas as pd

In [47]:
london = pd.read_csv('data/london.csv')

In [48]:
london.head()

Total      Sport  Age  Height  Weight Sex
0      0       Judo   23   170.0    60.0   M
1      0  Athletics   33   193.0   125.0   M
2      0  Athletics   30   187.0    76.0   M
3      0     Boxing   24     NaN     NaN   M
4      0  Athletics   26   178.0    85.0   F

In [51]:
m = 0.
for a in london['Age'].values:
    m += a
m /= len(london['Age'])
print m

26.0688559322


In [70]:
a = tf.placeholder(dtype = tf.float32, name = 'idade')
n_a = tf.placeholder(dtype = tf.float32, name = 'nro-de-idades')
m = tf.Variable(0.0, dtype = tf.float32, name = 'media')
acm_a = tf.assign(m, m + a)
avg = m / n_a

init = tf.global_variables_initializer()

In [72]:
with tf.Session() as s:
    s.run(init)
    for age in london['Age'].values:
        s.run(acm_a, feed_dict = {a: float(age)})
    mval = s.run(avg, feed_dict = {n_a: float(len(london['Age']))})
    print mval

26.0689


In [74]:
ages = tf.placeholder(dtype = tf.float32, name = 'idades')
avg = tf.reduce_mean(ages)

In [76]:
with tf.Session() as s:
    val = s.run(avg, feed_dict = {ages: london['Age'].values})
    print val

26.0689


In [3]:
import tensorflow as tf

In [4]:
cont = 0
while cont < 5:
    print cont
    cont = cont + 1

0
1
2
3
4


In [6]:
cont = tf.Variable(0, dtype = tf.int32, name = 'contador')
incr = tf.assign(cont, cont + 1)

init = tf.global_variables_initializer()

In [10]:
with tf.Session() as s:
    s.run(init)
    res = cont.eval()
    while res < 5:
        res = s.run(incr)
        print res

1
2
3
4
5


In [8]:
with tf.Session() as s:
    s.run(init)
    res = s.run(incr)
    print res

1
