In [1]:
import numpy as np

In [2]:
def mul(m1, m2):
    mr = np.zeros((m1.shape[0], m2.shape[1]))
    for i in range(m1.shape[0]):
        for j in range(m2.shape[1]):
            for k in range(m1.shape[1]):
                mr[i][j] += m1[i][k] * m2[k][j]
    return mr

In [3]:
m1 = np.random.rand(100, 15)
m2 = np.random.rand(15, 110)

In [4]:
mul(m1, m2)

array([[3.91339547, 2.70917172, 3.54623378, ..., 2.94147986, 4.21146565,
        3.67838419],
       [4.76132882, 3.51630504, 3.89187687, ..., 3.97848322, 5.01914875,
        4.59665574],
       [3.73151719, 2.79648854, 2.63897866, ..., 3.53664714, 4.14881   ,
        3.4819296 ],
       ...,
       [3.45885336, 3.2513792 , 3.45030575, ..., 2.32875312, 4.22736762,
        3.65260429],
       [4.91210151, 2.75311898, 3.71608866, ..., 4.14460892, 4.15779273,
        3.79390371],
       [3.03139731, 3.1084668 , 3.0661128 , ..., 2.04739179, 3.87843312,
        2.81452002]])

In [5]:
%timeit mul(m1, m2)

1 loop, best of 3: 125 ms per loop


In [14]:
%timeit np.matmul(m1, m2)

The slowest run took 6.90 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 3: 20.3 µs per loop


In [7]:
125000/20.7

6038.647342995169

In [8]:
import tensorflow as tf

In [9]:
t1 = tf.constant(np.random.rand(100, 15), dtype = tf.float32)
t2 = tf.constant(np.random.rand(15, 110), dtype = tf.float32)

In [13]:
t3 = tf.matmul(t1, t2)

In [15]:
t3

<tf.Tensor 'MatMul:0' shape=(100, 110) dtype=float32>

In [16]:
with tf.Session() as s:
    print(s.run(t3))

[[4.666102  2.4169302 4.1782703 ... 4.437763  2.7638974 3.1665502]
 [3.2213469 3.0366454 3.4782772 ... 3.3809547 3.150714  3.4014783]
 [4.43037   2.4688265 4.506041  ... 3.9627442 2.3388894 2.9474144]
 ...
 [3.4876692 2.9836946 3.4770057 ... 3.4859517 2.73291   3.7067409]
 [3.9826703 2.1219165 3.9497666 ... 4.3032217 3.2240555 3.5391896]
 [3.963118  2.1283212 3.6194992 ... 3.0308645 2.036427  2.9857416]]


In [17]:
def sigmoid(t):
    return 1.0/(1.0+tf.exp(t))

In [19]:
t1s = sigmoid(t1)

In [20]:
with tf.Session() as s:
    print(s.run(t1s))

[[0.30296642 0.48637217 0.28249207 ... 0.4603621  0.35841608 0.45189556]
 [0.3176203  0.4375327  0.4917469  ... 0.3349186  0.28978753 0.31985885]
 [0.3814723  0.35032538 0.41512015 ... 0.37215143 0.286961   0.42852652]
 ...
 [0.37907723 0.3632793  0.49617016 ... 0.33103883 0.43652987 0.3260305 ]
 [0.2969817  0.4333761  0.34723943 ... 0.4899493  0.35004064 0.30472004]
 [0.45565954 0.37043288 0.30280054 ... 0.35398382 0.44014588 0.4529571 ]]
